name: 'Amazon ECS "Run Task" Action for GitHub Actions'
description: 'Runs a single ECS task from a base task definition with overrides'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The family and revision (family:revision ) or full ARN of the task definition to run. If a revision is not specified, the latest ACTIVE revision is used.'
    required: true
  aws-credentials:
    description: 'Json array of AWS credentials to connect to ECS'
    required: true
  capacity-provider-strategy:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  cluster:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
  count:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
  enable-ecs-managed-tags:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
    default: false
  enable-execute-command:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
    default: false
  group:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: false
  launch-type:
    description: 'The infrastructure on which to run your standalone task. For more information, see Amazon ECS launch types in the Amazon Elastic Container Service Developer Guide '
    required: false
  network-configuration:
    description: 'The network configuration for the task. This parameter is required for task definitions that use the awsvpc network mode to receive their own elastic network interface, and it is not supported for other network modes'
    required: false
  overrides:
    description: 'A list of container overrides in JSON format that specify the name of a container in the specified task definition and the overrides it should receive.'
    required: false
  placement-constraints:
    description: 'A list of container overrides in JSON format that specify the name of a container in the specified task definition and the overrides it should receive.'
    required: false
    default: '[]'
  placement-strategy:
    description: 'A list of container overrides in JSON format that specify the name of a container in the specified task definition and the overrides it should receive.'
    required: false
    default: '[]'
  platform-version:
    description: 'A list of container overrides in JSON format that specify the name of a container in the specified task definition and the overrides it should receive.'
    required: false
    default: 'LATEST'
  started-by:
    description: 'An optional tag specified when a task is started. For example, if you automatically trigger a task to run a batch process job, you could apply a unique identifier for that job to your task with the startedBy parameter. You can then identify which tasks belong to that job by filtering the results of a ListTasks call with the startedBy value. Up to 36 letters (uppercase and lowercase), numbers, hyphens, and underscores are allowed.'
    required: false
    default: 'github_actions'
  tags:
    description: 'A list of tags for the container'
    required: false
    default: '[]'
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'index.js'
